---
version: 2.0
builds:
  build-gpu-operator:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make && \
               HOURLY_TAG_LABEL=$RELEASE IMAGE_TAG=latest make docker-build && \
               IMAGE_TAG=latest make docker-save && \
               make bundle-build && \
               make bundle-save"]
    owners: ["email:mharkara@amd.com"]
    artifacts:
     - /gpu-operator/amd-gpu-operator-latest.tar.gz
     - /gpu-operator/amd-gpu-operator-olm-bundle.tar.gz
    repo-dependencies:
      /ws/builder/kernel-module-management:
        repository: https://github.com/pensando/kernel-module-management
        reference: main

  build-gpu-operator-k8s:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make && \
               IMAGE_TAG=latest PROJECT_VERSION=1.0.0 make helm"]
    owners: ["email:mharkara@amd.com"]
    artifacts:
     - /gpu-operator/helm-charts-k8s/gpu-operator-helm-k8s-1.0.0.tgz
    repo-dependencies:
      /ws/builder/kernel-module-management:
        repository: https://github.com/pensando/kernel-module-management
        reference: main

  build-gpu-operator-openshift:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make && \
               IMAGE_TAG=latest OPENSHIFT=1 PROJECT_VERSION=1.0.0 make helm"]
    owners: ["email:mharkara@amd.com"]
    artifacts:
     - /gpu-operator/helm-charts-openshift/gpu-operator-helm-openshift-1.0.0.tgz
    repo-dependencies:
      /ws/builder/kernel-module-management:
        repository: https://github.com/pensando/kernel-module-management
        reference: main

targets:
  gpu-operator-sanity:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && \
                                    make generate && \
                                    make vet && \
                                    make lint && \
                                    make unit-test"]
    owners: ["email:mharkara@amd.com"]
    area:
    sub-area:
  copyright-checks:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make copyrights"]
    owners: ["email:sajmera@amd.com"]
    area:
    sub-area:
    feature:

image:
  bind_dir: "/gpu-operator"
  work_dir: "/gpu-operator"
  
jobs:
  api:
    labels: ["CI-Precheckin-Gpuoperator"]
  asset-build:
    labels: ["CI-Sanity-Build"]
