---
version: 2.0
builds:
  build-gpu-operator:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make && \
               HOURLY_TAG_LABEL=$RELEASE IMAGE_TAG=latest make docker-build && \
               IMAGE_TAG=latest make docker-save && \
               make bundle-build && \
               make bundle-save"]
    owners: ["email:mharkara@amd.com"]
    artifacts:
     - /gpu-operator/amd-gpu-operator-latest.tar.gz
     - /gpu-operator/amd-gpu-operator-olm-bundle.tar.gz
    repo-dependencies:
      /ws/builder/kernel-module-management:
        repository: https://github.com/pensando/kernel-module-management
        reference: main

  build-gpu-operator-k8s:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make && \
               IMAGE_TAG=latest PROJECT_VERSION=v1.0.0 make helm"]
    owners: ["email:mharkara@amd.com"]
    artifacts:
     - /gpu-operator/helm-charts-k8s/gpu-operator-helm-k8s-v1.0.0.tgz
    repo-dependencies:
      /ws/builder/kernel-module-management:
        repository: https://github.com/pensando/kernel-module-management
        reference: main

  build-gpu-operator-openshift:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make && \
               IMAGE_TAG=latest OPENSHIFT=1 PROJECT_VERSION=v1.0.0 make helm"]
    owners: ["email:mharkara@amd.com"]
    artifacts:
     - /gpu-operator/helm-charts-openshift/gpu-operator-helm-openshift-v1.0.0.tgz
    repo-dependencies:
      /ws/builder/kernel-module-management:
        repository: https://github.com/pensando/kernel-module-management
        reference: main

targets:
  gpu-operator-sanity:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && \
                                    make generate && \
                                    make vet && \
                                    make lint && \
                                    make unit-test"]
    owners: ["email:mharkara@amd.com"]
    area:
    sub-area:
  copyright-checks:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make copyrights"]
    owners: ["email:sajmera@amd.com"]
    area:
    sub-area:
    feature:

  operator-e2e-sim:
    commands: ["sh", "-cx",
    "cd ci-internal && ./setup_e2e.sh;
    cd ../ && SIM_ENABLE=1 make && SIM_ENABLE=1 make docker-push && helm repo add jetstack https://charts.jetstack.io --force-update && helm install cert-manager jetstack/cert-manager --namespace cert-manager  --create-namespace --version v1.15.1 --set crds.enabled=true && SIM_ENABLE=1 make helm-install && sleep 60 && kubectl get pods -A | grep amd && CI_ENV=1 SIM_ENABLE=1 make -C tests/e2e/ && kubectl get pods -A | grep amd"]
    owners: ["email:sajmera@amd.com"]
    queue_name: ubuntu2204
    area:
    sub-area:
    feature:
    repo-dependencies:
      /ws/builder/kernel-module-management:
        repository: https://github.com/pensando/kernel-module-management
        reference: main
image:
  bind_dir: "/gpu-operator"
  work_dir: "/gpu-operator"
  
jobs:
  api:
    labels: ["CI-Precheckin-Gpuoperator"]
  asset-build:
    labels: ["CI-Sanity-Build"]
      # ci-internal:
    #    labels: [""]
host_mounts:
  "/sys/module": "/sys/module"
  "/lib/modules": "/lib/modules"
