---
version: 2.0
builds:
  build-gpu-operator:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make && \
               IMAGE_TAG=latest make docker-build && \
               IMAGE_TAG=latest make docker-save && \
               make bundle-build && \
               make bundle-save"]
    owners: ["email:mharkara@amd.com"]
    artifacts:
     - /gpu-operator/amd-gpu-operator-latest.tar.gz
     - /gpu-operator/amd-gpu-operator-bundle.tar.gz

  build-gpu-operator-k8s:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make && \
               IMAGE_TAG=latest make helm"]
    owners: ["email:mharkara@amd.com"]
    artifacts:
     - /gpu-operator/helm-charts-k8s/gpu-operator-0.0.1.tgz

  build-gpu-operator-openshift:
    commands: ["sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && make && \
               IMAGE_TAG=latest OPENSHIFT=1 make helm"]
    owners: ["email:mharkara@amd.com"]
    artifacts:
     - /gpu-operator/helm-charts-openshift/gpu-operator-0.0.1.tgz

targets:
  test:
    commands: [ "/bin/sh", "-c", "cd /usr/src/github.com/pensando/gpu-operator && \
                                    make generate && \
                                    make vet && \
                                    make lint"]
    owners: ["email:mharkara@amd.com"]
    area:
    sub-area:

image:
  bind_dir: "/gpu-operator"
  work_dir: "/gpu-operator"
  
jobs:
  api:
    labels: ["CI-Precheckin-Gpuoperator"]
  asset-build:
    labels: ["CI-Sanity-Build"]
