---
version: 2.0
targets:
  operator-sim:
    commands: ["sh", "-cx",
    "./deploy_k8s_by_kind.sh; ls -al ~/.kube; cat ~/.kube/config;
    kubectl cluster-info; kubectl get pods -A; kubectl get nodes -o wide;
    helm repo add jetstack https://charts.jetstack.io --force-update;
    helm install cert-manager jetstack/cert-manager --namespace cert-manager  --create-namespace --version v1.15.1 --set crds.enabled=true;
    wget https://github.com/ROCm/gpu-operator/releases/download/v1.0.0/gpu-operator-charts-v1.0.0.tgz;
    helm install gpu-operator ./gpu-operator-charts-v1.0.0.tgz -n kube-amd-gpu --create-namespace;
    kubectl get pods -A"]
    owners: ["email:qiwa@pensando.io"]
    area:
    sub-area:
    feature:

image:
  bind_dir: "/go/src/github.com/pensando/gpu-operator"
  work_dir: "/go/src/github.com/pensando/gpu-operator/ci-internal"
