controller:
  manager:
    args:
    - --config=controller_config.yaml
    containerSecurityContext:
      allowPrivilegeEscalation: false
    env:
      relatedImageBuild: gcr.io/kaniko-project/executor:v1.23.2
      relatedImageSign: gcr.io/k8s-staging-kmm/kernel-module-management-signimage:v20240618-v2.1.1
      relatedImageWorker: gcr.io/k8s-staging-kmm/kernel-module-management-worker:v20240618-v2.1.1
    image:
      repository: gcr.io/k8s-staging-kmm/kernel-module-management-operator
      tag: v20240618-v2.1.1
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 384Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
controllerMetricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
kubernetesClusterDomain: cluster.local
managerConfig:
  controllerConfigYaml: |-
    healthProbeBindAddress: :8081
    webhookPort: 9443
    leaderElection:
      enabled: true
      resourceID: kmm.sigs.x-k8s.io
    metrics:
      enableAuthnAuthz: true
      bindAddress: 0.0.0.0:8443
      secureServing: true
    worker:
      runAsUser: 0
      seLinuxType: spc_t
      setFirmwareClassPath: /var/lib/firmware
webhookServer:
  replicas: 1
  webhookServer:
    args:
    - --config=controller_config.yaml
    - --enable-module
    - --enable-namespace
    - --enable-preflightvalidation
    containerSecurityContext:
      allowPrivilegeEscalation: false
    image:
      repository: gcr.io/k8s-staging-kmm/kernel-module-management-webhook-server
      tag: latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 384Mi
      requests:
        cpu: 10m
        memory: 64Mi
webhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
