node-feature-discovery:
  enabled: true  # Set to false to disable the subchart
kmm:
  enabled: true  # Set to false to disable the subchart
installdefaultNFDRule: true # default NFD rule will detect amd gpu based on pci vendor ID
controllerManager:
  manager:
    args:
    - --config=controller_manager_config.yaml
    containerSecurityContext:
      allowPrivilegeEscalation: false
    image:
      repository: yan1996/amd-gpu-operator
      tag: latest
    imagePullPolicy: Always
    resources:
      limits:
        cpu: 500m
        memory: 384Mi
      requests:
        cpu: 10m
        memory: 64Mi
  replicas: 1
  serviceAccount:
    annotations: {}
kmmDevicePlugin:
  serviceAccount:
    annotations: {}
kmmModuleLoader:
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local
managerConfig:
  controllerManagerConfigYaml: |-
    healthProbeBindAddress: :8081
    metricsBindAddress: 127.0.0.1:8080
    leaderElection:
      enabled: true
      resourceID: gpue.openshift.io
metricsService:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  type: ClusterIP
nodeLabeller:
  serviceAccount:
    annotations: {}
