apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-charts-openshift.fullname" . }}-controller-manager
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-openshift.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-charts-openshift.fullname" . }}-kmm-device-plugin
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-openshift.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.kmmDevicePlugin.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-charts-openshift.fullname" . }}-kmm-module-loader
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-openshift.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.kmmModuleLoader.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helm-charts-openshift.fullname" . }}-node-labeller
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
  {{- include "helm-charts-openshift.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.nodeLabeller.serviceAccount.annotations | nindent 4 }}