apiVersion: v1
kind: ConfigMap
metadata:
  name: amd-smi-cmds
data:
  run.sh: |
    #!/bin/bash
    sudo amd-smi set -g all -c sclk 1
    amd-smi static --clock
---
apiVersion: batch/v1
kind: Job
metadata:
  name: amd-smi-job
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        name: amd-smi-job
    spec:
      nodeSelector:
        # modify the nodeSelector here to specify which node to execute the job
        kubernetes.io/hostname: <your node name>
      restartPolicy: Never
      initContainers:
      - name: amd-smi-init
        image: docker.io/rocm/rocm-terminal:6.4
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash", "/opt/configmap/run.sh"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev
          mountPath: /dev
        - name: sys
          mountPath: /sys
        - name: amd-smi-cmds
          mountPath: /opt/configmap
          readOnly: true
      containers:
      - name: config-applied
        image: docker.io/rocm/rocm-terminal:6.4
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "echo 'amd-smi configuration applied successfully' && amd-smi static --clock"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: dev
          mountPath: /dev
        - name: sys
          mountPath: /sys
      volumes:
      - name: dev
        hostPath:
          path: /dev
          type: Directory
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      - name: amd-smi-cmds
        configMap:
          name: amd-smi-cmds
          defaultMode: 0755

