apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-charts.fullname" . }}-controller-manager-metrics-service
  labels:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
    control-plane: controller-manager
  {{- include "helm-charts.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    app.kubernetes.io/component: amd-gpu
    app.kubernetes.io/name: amd-gpu
    app.kubernetes.io/part-of: amd-gpu
    control-plane: controller-manager
  {{- include "helm-charts.selectorLabels" . | nindent 4 }}
  ports:
	{{- .Values.metricsService.ports | toYaml | nindent 2 }}