{{- if eq .Values.platform "openshift" }}
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: {{ .Release.Name }}-nfd-worker-scc
allowPrivilegedContainer: true
allowHostDirVolumePlugin: true
allowHostNetwork: true
allowHostPorts: true
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
users:
{{- if index .Values "node-feature-discovery" "enabled" }}
- system:serviceaccount:{{ .Release.Namespace }}:{{ .Release.Name }}-node-feature-discovery-worker
{{- else }}
- system:serviceaccount:{{ index .Values "openshift" "nfd-namespace" }}:{{ index .Values "openshift" "nfd-worker-sa" }}
{{- end }}
{{- end }}