site_name: AMD GPU OPERATOR
nav:
  - Introduction: index.md
  - Components: components.md
  - Install:
    - Install Operator:
        - Vanilla Kubernetes - Helm Charts: vanilla_k8s_deploy_helm.md
        - OpenShift - Helm Charts: openshift_deploy_helm.md
        - OpenShift - OLM bundle: openshift_deploy_olm.md
    - Deploy Driver:
      - Install Driver: driver_install.md
      - Pre-Compiled Driver Image: pre_compiled_image.md
      - Secure Boot Driver Image: secure_boot.md
  - Upgrade:
    - Upgrade Operator: operator_upgrade.md
    - Upgrade Driver: driver_upgrade.md
    - Upgrade Kernel: kernel_upgrade.md
  - Uninstall:
    - Unload Driver: driver_unload.md
    - Uninstall Operator: operator_uninstall.md
  - TroubleShooting: troubleshoot.md
  - Specialized Networks:
    - HTTP Proxy: http_proxy.md
    - Air-Gapped Network: airgapped_network.md
theme: 
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - dockerfile
    - shell
    - yaml
markdown_extensions:
  - admonition
repo_url: https://github.com/pensando/gpu-operator
edit_uri: blob/main/docs/docs/
copyright: Copyright © 2024-2025, Advanced Micro Devices, Inc.
